<?xml version="1.0"?>
<package format="3">
  <name>yopo_bringup</name>
  <version>0.0.1</version>
  <description>ROS2 launch entry for YOPO planner.</description>
  <maintainer email="duckcity@example.com">duckcity</maintainer>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>so3_quadrotor_simulator</exec_depend>
  <exec_depend>sensor_simulator</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
